name: Deploy Go App to EC2

on:
    push:
        branches:
            - master  # <-- твоя ветка, не main

jobs:
    deploy:
        name: Deploy via SSH
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up SSH key
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

            - name: Deploy to EC2
              run: |
                  ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
                    set -e
                    cd /opt/go-app
                    git pull origin master
                    go build -o app -buildvcs=false
                    sudo systemctl restart goapp.service
                  EOF
